openapi: 3.1.0
info:
    version: 1.0.0
    title: Contacts
    license:
        name: Apache 2.0
        url: http://www.apache.org/licenses/LICENSE-2.0.html
    description: This is a documentation for Contacts app
tags:
    - name: Contacts
      description: Contact operations
    - name: Auth
      description:
          Auth operations
          # теги, що ви будете використовувати
servers:
    - url: http://localhost:8080
    paths:
      /contacts/{id}:
        get:
          $ref: ../swagger/paths/contacts/{id}/get.yaml
components:
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
